version: 1.0
os: linux
files:
  - source: /
    destination: /usr/module-interview/src
    overwrite: true
permissions:
  - object: /usr/module-interview/src/codedeploy
    pattern: "*.sh"
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: codedeploy/before_install.sh
      timeout: 180
  AfterInstall:
    - location: codedeploy/after_install.sh
      timeout: 180
  ApplicationStart:
    - location: codedeploy/app_start.sh
      timeout: 180
  ApplicationStop:
    - location: codedeploy/app_stop.sh
      timeout: 180
  ValidateService:
    - location: codedeploy/validate_service.sh
      timeout: 180